name: Run unit tests

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  pull_request:

jobs:
  unit-test:
    name: Run unit tests over pyRDDLGym
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install dependencies
        run: pip install -r requirements.txt